spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        bitcoin-in:
          destination: bitcoin
          contentType: application/json
        bitcoin-out:
          destination: bitcoin
          contentType: application/json

external:
  ticker:
    uri: https://api.coindesk.com/v1/%s/currentprice.json